# The URL to download the app from the app store
AppDownloadUrl__Android: "https://play.google.com/store/apps/details?id=com.equinecastration.app"
AppDownloadUrl__iOS: "https://apps.apple.com/gb/app/equine-castration-research/id6472803784"

OutboundEmail__FromName: "Equine Castration Complications"
