name: Build Equine Castration React-Native app preview

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - app/react-native-app/**
      - .github/workflows/build.react-native-app.yml

env:
  # Configure these
  CI_node-version: "16"
  CI_package: react-native-app
  Platform: android
  Profile: preview
  API_URL: ${{ secrets.API_URL }}
  EQUINE_CASTRATION_IDENTIFIER: ${{ secrets.EQUINE_CASTRATION_IDENTIFIER }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.CI_node-version }}
          cache: pnpm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: Setup EAS local builds
        run: yarn global add eas-cli-local-build-plugin

      - run: pnpm i --frozen-lockfile --filter ${{ env.CI_package }}

      - name: Build app preview
        working-directory: app/react-native-app
        run: |
          mkdir -p android/keystores
          echo ${{ secrets.RELEASE_KEYSTORE_BASE64 }} | base64 -d > android/keystores/release.keystore
          echo ${{ secrets.CREDENTIALS_JSON_BASE64 }} | base64 -d > credentials.json
          echo "LOCAL_PUBLIC_API=${API_URL}" >> .env
          echo "EQUINE_CASTRATION_IDENTIFIER=${EQUINE_CASTRATION_IDENTIFIER}" >> .env
          eas build --local \
            --non-interactive \
            --output=./app-preview-build.apk \
            --platform=${{ env.Platform }} \
            --profile=${{ env.Profile }}

      - name: 📱 Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ env.Platform }}
          path: app/react-native-app/app-preview-build.apk
