name: Deploy Dev
on:
  workflow_dispatch:
    inputs:
      publish-run-id:
        description: The Workflow Run ID for a successful Publish of the Equine Castration
        required: true
        type: string
      publish-migration-artifact:
        description: Migrations artifact name from the workflow matching the publish-run-id
        required: true
        type: string
      publish-dotnet-artifact:
        description: dotnet artifact name from the workflow matching the publish-run-id
        required: true
        type: string

env:
  run-id: ${{ github.event.inputs.publish-run-id }}
  bundleExecutable_migration: migrate-equine-castration-db # CI_migration-output-filename from the publish workflow
  dotnet-version: 6.0.x # dotnet version to use
  az-app-service: dev-equinecastration # name of the app service to deploy to

  migration-artifact: ${{ github.event.inputs.publish-migration-artifact }}
  dotnet-artifact: ${{ github.event.inputs.publish-dotnet-artifact }}

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    steps:
      # download artifacts from the run we want on the release
      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ env.run-id }}
          name: ${{ env.migration-artifact }}

      - name: Apply Migrations
        run: |
          chmod +x ${{ env.bundleExecutable_migration}}
          ./${{ env.bundleExecutable_migration }} --connection "${{ secrets.DB_CONNECTION_STRING }}"

  deploy-backend:
    needs: deploy-migrations # wait for migrations to complete
    runs-on: ubuntu-latest
    steps:
      # download artifacts from the run we want on the release
      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ env.run-id }}
          name: ${{ env.dotnet-artifact }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.az-app-service }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
