# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Backend API

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_PACKAGE_PATH: "app/EquineCastration"
  DOTNET_VERSION: "8.x"
  DATA_PROJECT: ./app/Data/Data.csproj
  WEB_APP_PROJECT: ./app/EquineCastration/EquineCastration.csproj
  DOTNET_BUILD_CONFIG: release
  NODE_VERSION: "16.x"
  CLIENT_PACKAGE: "client-app"

jobs:
  # Publish Db Migrations
  publish_DbMigrations:
    name: Publish Database Migrations Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore repo dotnet tools
        run: dotnet tool restore
        shell: bash

      - name: Build bundle
        run: dotnet ef migrations bundle -p ${{ env.WEB_APP_PROJECT }} -o ${{ github.workspace }}/efbundle -r linux-x64 --self-contained --configuration ${{ env.DOTNET_BUILD_CONFIG }}
        shell: bash

      - name: Publish migrations bundle artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}
          name: migrations

  # publish the web frontend
  publish-web-frontend:
    name: Publish Web Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.30.0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION}}
          cache: pnpm

      - run: pnpm i --frozen-lockfile --filter ${{ env.CLIENT_PACKAGE }}

      - run: pnpm --filter ${{ env.CLIENT_PACKAGE }} build

      - name: Publish web frontend artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./app/client-app/dist
          name: web-frontend

  # Publish Web App
  publish_webapp:
    name: Publish Web App
    needs: [publish-web-frontend]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Git Commit Hash
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "GitHash=$calculatedSha" >> $GITHUB_ENV

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Download web frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: web-frontend
          path: ./app/client-app/dist

      - name: dotnet publish
        run: dotnet publish ${{ env.WEB_APP_PROJECT }} -c ${{ env.DOTNET_BUILD_CONFIG }} -o ${{ github.workspace }} -p:GitHash=${{ env.GitHash }}
        shell: bash

      - name: Publish webapp artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}
          name: webapp

  # Deploy UAT
  deploy-uat:
    name: Deploy UAT
    needs: [publish_DbMigrations, publish_webapp]
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_BACKEND_NAME: dev-equinecastration # name of the app service to deploy to
    environment: uat

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set Git Permissions
        run: chmod -R +rwx .git

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          path: migrations
          name: migrations

      - name: Run Migrations
        run: |
          chmod +x ./efbundle
          ./efbundle --connection "${{ secrets.UAT_DB_CONNECTION_STRING }}"
        working-directory: ${{ github.workspace }}/migrations
        shell: bash

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          path: webapp
          name: webapp

      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_BACKEND_NAME }}
          publish-profile: ${{ secrets.UAT_AZUREAPPSERVICE_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/webapp
